---
# This Github workflow will run jobs to build java-app.
name: spring-petclinic

on:
  schedule:
  - cron: '0 0 * * *' # every night at 12:00AM UTC
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  full:
    uses: ploigos/ploigos-github-workflows/.github/workflows/full.yaml@46-add-static-image-scan-compliance-step-w-openscap-to-full-pipeline
    secrets: inherit
